(function () {
  window.GameEvents = Object.freeze({
    COMBO_UPDATED: "comboUpdated",
    CONSOLE_SYMBOL_ADDED: "consoleSymbolAdded",
    CONSOLE_SELECTION_OPENED: "consoleSelectionOpened",
    CONSOLE_SELECTION_CLOSED: "consoleSelectionClosed",
    DISPLAY_RESOLUTION_CHANGED: "displayResolutionChanged",
    FIRST_LINE_SOLVED: "first-line-solved",
    PROBLEM_COMPLETED: "problemCompleted",
    PROBLEM_LINE_COMPLETED: "problemLineCompleted",
    PURPLE_WORM_TRIGGERED: "purpleWormTriggered",
    ROW_RESET_BY_WORM: "rowResetByWorm",
    STEP_COMPLETED: "stepCompleted",
    SYMBOL_CLICKED: "symbolClicked",
    SYMBOL_REVEALED: "symbolRevealed",
    WORM_CURSOR_TAP: "wormCursorTap",
    WORM_CURSOR_UPDATE: "wormCursorUpdate",
    WORM_SYMBOL_CORRECT: "wormSymbolCorrect",
    WORM_SYMBOL_SAVED: "wormSymbolSaved",
    PRELOAD_PROGRESS: "preloadProgress",
    PRELOAD_READY: "preloadReady",
    PRELOAD_FAILED: "preloadFailed",
    STARTUP_PRELOAD_FORCE_COMPLETE: "startupPreloadForceComplete",
    EVAN_HELP_STARTED: "evanHelpStarted",
    EVAN_HELP_STOPPED: "evanHelpStopped",
    EVAN_ACTION_REQUESTED: "evanActionRequested",
    EVAN_ACTION_COMPLETED: "evanActionCompleted",
    INSTALL_PROMPT_AVAILABLE: "installPromptAvailable",
    INSTALL_PROMPT_DISMISSED: "installPromptDismissed",
    GAMEPLAY_READY_CHANGED: "gameplayReadyChanged",
    GAMEPLAY_INPUT_LOCK_CHANGED: "gameplayInputLockChanged",
    BRIEFING_DISMISSED: "briefingDismissed",
    STARTUP_PRELOAD_COMPLETE: "startupPreloadComplete",
  });
})();
